### ISSUE TITLE
Border width problem

### ISSUE THREAD

**Issue by mick-wieland** [j26design/Mailchimp#1]
Hi John, 

I'm using the new Mailchimp 1-1 widget (v. 2.2.0) and the border width setting under "Input Styling" only works when it's set the same for all four sides. When I try to set the width for only certain sides, it does nothing. See screenshot:
https://www.dropbox.com/s/8at9udj31f6ueda/Screenshot%202016-05-16%2014.30.42.png?dl=0

Here is a screenshot of the form with the input border width set to 2 pixels for the bottom border. You can see it has no effect:
https://www.dropbox.com/s/mocv1i2w0a5asti/Screenshot%202016-05-16%2014.30.49.png?dl=0

**Comment by jp26jp** [comment]
Thank you for reporting this. I'll take a look. One moment.

**Comment by jp26jp** [comment]
Okay, I found the issue and updated the widgets. If you have a Lifetime membership then the widgets should be synced. If not, if you redownload the widgets that were sent in the email, you'll download the updated version of them.

I'm going to close this issue but if the update doesn't fix the problem, you'll be able to reopen the issue and I'll take another look.
