### ISSUE TITLE
text input color

### ISSUE THREAD

**Issue by Bchila** [j26design/Mailchimp#2]
John, need help. I cant change the state of text color for my 4-1-1-1 mailchimp widget. Display text is white, background is black, but when i go live, the input text for field also types black, so not visible against black background. Can you help?  thanks!

**Comment by jp26jp** [comment]
Thank you for reporting it here! 

I might not need it, but would you mind uploading the .[muse file here](https://www.dropbox.com/request/IZ9vUxuqIFgTUbKYGXon)?

**Comment by jp26jp** [comment]
I can't seem to reproduce the issue so I will [actually need your .muse](https://www.dropbox.com/request/IZ9vUxuqIFgTUbKYGXon) file if you don't mind.

**Comment by Bchila** [comment]
uploaded

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16

**Comment by Bchila** [comment]
update, upload finally went through via your DB lilnk

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16

**Comment by Bchila** [comment]
so after looking further into this, it looks as though my 4-1 (v2.1) widget has the "label styling" option grayed out so i cant edit it, but i can use the input styling option to change color of labels for each input box (not the input text itself when someone enters their info) make sense?

**Comment by jp26jp** [comment]
So there is a new version of the widgets that was released and sent out via email. Check your spam folder to see if it's there. 4-1 is now 1-1-1-1. The email explains the change in titles. I'll double check to make sure that you're on the update mailing list.

**Comment by Bchila** [comment]
got the updated widget from dropbox, im a lifetime member ;)  it worked, 
thanks!

Regards,
Brett Chila
Owner/Designer
Triune Design Studio
Jacksonville, Florida USA
Office: 1.904.300.3474

www.TriuneDesignStudio.com          (website)
www.Behance.net/TriuneMultimedia    (online portfolio)
www.Facebook.com/TriuneDesignStudio (Facebook)
www.LinkedIn.com/in/BrettChila      (LinkedIn)
www.Google.com/+TriuneMultimedia    (Google+)

Graphic Design | Video/Motion Graphics | Websites & Hosting Solutions

"Specializing in Graphic Design for the Apparel Industry"

"For God so loved the world, that He sent His one & only Son,
that whosoever would believe in Him, would not perish,
but have eternal life."  -John 3:16

**Comment by jp26jp** [comment]
Oh awesome!! So glad it worked. Feel free to open up another issue if you run into another error!
