### ISSUE TITLE
Pop-up Problems 

### ISSUE THREAD

**Issue by docbeyer** [j26design/Mailchimp#3]
Hello,

I've added the Mail chimp widget to my muse website and followed the setup instructions (linked to Mailchimp, enabled and linked segments, ect.) I published my site but when I tested it out the pop up said it can't find the page. I've tried multiple times in both safari and chrome but no luck. In addition to that it's not submitting the email to my Mailchimp lists or sending a confirmation email when I try to sign up using the widget. I've attached screen shots of the problem in safari and chrome. Any help with this would be greatly appreciated.

Thanks,
Tony

![screen shot 2016-06-12 at 7 35 32 pm](https://cloud.githubusercontent.com/assets/19899377/15997391/edc08268-30f8-11e6-9cfb-884a5848934b.png)
![screen shot 2016-06-12 at 11 30 27 pm](https://cloud.githubusercontent.com/assets/19899377/15997395/f13cdc02-30f8-11e6-90e0-825300e29d0a.png)

**Comment by jp26jp** [comment]
That's very strange. Would you mind uploading your .[muse file here](https://www.dropbox.com/request/IZ9vUxuqIFgTUbKYGXon)?

**Comment by docbeyer** [comment]
I just sent over the file (BLUFORA.muse). Thank you.

**Comment by jp26jp** [comment]
taking a look now

**Comment by docbeyer** [comment]
Sounds good thank you.

**Comment by docbeyer** [comment]
Did you get a chance to look into this issue?

**Comment by jp26jp** [comment]
You didn't include the 2 forward slashes. Once you include those, it works
