### ISSUE TITLE
mailchimp widget button

### ISSUE THREAD

**Issue by trevfury** [j26design/Mailchimp#4]
The widget works good.  I'd like to be able to move the fields and button around freely, if it's possible.  I'd also like to be able to have more control of the look of the button.  Ideally, I'd like to be able to put my own button image in there.

**Comment by jp26jp** [comment]
The first request isn't possible because Muse doesn't give developers the ability to do that but the second part is possible and I will definitely add that as a feature!

**Comment by jp26jp** [comment]
This feature was added to one of the updates a while back.
